### PR TITLE
UPBGE: Add an option to debug light shadow frustum and try to check intersection (old)

### PR DESCRIPTION
**Pull request by youle31**
see old branch for comments. up to date with master 03/03/2017

### CODE REVIEW

**Comment by youle31** [comment]
This needs to be rewritted in my opinion. And DrawDebugCameraBox too...

To make the method BoxInsideFrustum work, we have to contruct the box exactly as it is done in: MT_Vector3 box[8];
gameobj->GetSGNode()->GetBBox(box);

Else BoxInsideFrustum won't work I think.

**Comment by youle31** [comment]
Not necessarly DrawDebugCameraBox. But we need a custom box for light compatible with BoxInsideFrustum, and why not take the same box to draw and to check if it is inside camera frustum?

**Comment by youle31** [comment]
it seems to ~work but in the drawing doesn't correspond exactly to the calculation of intersection...

**Comment by youle31** [comment]
test file: http://pasteall.org/blend/index.php?id=45804 (nothing works as expected...)

**Comment by youle31** [comment]
cam->GetModelviewMatrix() returns identity

**Comment by youle31** [comment]
So it seems my code is correct. It works in most cases but BoxInsideFrustum has an issue (a known issue on the net) because the computation is not 100% accurate and doesn't handle every case, particularly with large boxes. There are tons of articles which talk about frustum and box intersection, and possibility of optimizations. So it could be the occasion to refactor/optimize BoxInsideFrustum or in general culling computation.

**Comment by youle31** [comment]
needs refactor of BoxInsideFrustum

**Comment by panzergame** [comment]
@youle31 : Was the computing of the box using a matrix working ?

**Comment by youle31** [comment]
@panzergame : We can also try this: http://www.yosoygames.com.ar/wp/2016/12/frustum-vs-pyramid-intersection-also-frustum-vs-frustum/ for spots... Now that I ~understood how it works I guess I can implement it...

**Comment by youle31** [comment]
I close this as I have a new branch

**Pull request closed without merging**
