### PR TITLE
Ge lodoptimization

### PR DESCRIPTION
**Pull request by youle31**
Can't we avoid a for loop like that?

(there's another for loop in DrawDebug... I don't know if it can also be avoided)

(see last commit only)

edit: with 16000 cubes increases from 5fps (24 -> 29 fps) (20,8%)

### CODE REVIEW

**Comment by panzergame** [comment]
The cost of the loop itself (without its content) is not so big, maybe 5-10 instructions per iterations. For the moment is not grave. @youle31 : Instead can you investigate on these lines:
```
	// Handle dupligroups
	if (m_pInstanceObjects) {
		for (CListValue::iterator it = m_pInstanceObjects->GetBegin(), end = m_pInstanceObjects->GetEnd(); it != end; ++it) {
			KX_GameObject *instob = (KX_GameObject *)*it;
			instob->UpdateLod(cam_pos, lodfactor);
		}
	}
```
Objects in groups are not in objects scene list ? If it's the case then these lines are useless.
An other way to optimize the schmilblique is to multi task the function KX_GameObject:: UpdateLod but then set a mutex (or spin lock) before changing of mesh. But i'm not sure if it's great to use many task e.g 2000 tasks, if not then create 20 task for 100 objects ect…

**Comment by youle31** [comment]
optimization of 20.8% with 16000 cubes on my computer without script

**Comment by panzergame** [comment]
Well, loop cost most that what i though :P

What 20.8 %, how do you get how many ?? :).

**Comment by youle31** [comment]
5 * 100 / 24

**Comment by panzergame** [comment]
I mean how just merging a loop can save too much performance ? I'm surprised, it's nice.

**Comment by youle31** [comment]
I guess a loop threw 16000 objects has a certain cost

**Comment by panzergame** [comment]
I found the reason: we updated lod for every logic frame and not only for every render frame, and as default we run as much as possible logic frame to follow the user FPS (with the logic maximum frame limit sure).
The patch http://www.pasteall.org/70166 fix it.

@youle31 : Thanks for the issue report, nice hit :+1:

**Comment by youle31** [comment]
panzergame: your patch increase from 4 fps, mine of 5 fps, so I have 33/34 fps  now with both patches...

**Comment by youle31** [comment]
Oh no wait... I'll make other tests tomorrow... But the for loop has an impact. It's sure

**Comment by youle31** [comment]
http://www.pasteall.org/pic/103846 Master
http://www.pasteall.org/pic/103847 Master with your commit
http://www.pasteall.org/pic/103848 Master with my commit

**Comment by panzergame** [comment]
I commited the first patch for the moment, I don't very know about merging the loop…

**Pull request closed without merging**
