### PR TITLE
UPBGE: Fix python component conversion from async libload.

### PR DESCRIPTION
**Pull request by panzergame**
Previously the async thread dedicated for the libload was directly calling
python function without ensuring the GIL and this caused issue, no conversion
or memory error.

To fix this issue Py_X_ALLOW_THREADS and Py_X_THREADS macro are used, they
intent on ensuring and locking the python GIL so that any python API calls
are proceeded sequentially.

Fix issue #751.

### CODE REVIEW

**Comment by youle31** [comment]
Hi, it's weird I have no crash neither in master, neither in ge_bug_fix_751 but an issue with libload in the test file:

Sometimes, when I press P I have that:
weird
And sometimes that:
normal
(I just duplicated cube in asset_0.blend because I had thre same issue with default file and as I saw nothing...)

There is no special error message in the console (except what is printed in libload.blend). I don't really know how to debug that. The only thing I noticed is that Debug Properties text seems superposed when libload doesn't work.

**Comment by lordloki** [comment]
Tested but It keeps crashing. Instead of MACROS, I also tried with PyEval_Savethread/PyEvalRestoreThread (crashed) and PyGILState_Ensure/PyGILState_Release (freeze).

**Comment by lordloki** [comment]
Just for info, I'm trying to compile UPBGE under windows using Mingw64 to test if the threads issues improve.

**Comment by panzergame** [comment]
I pushed some fixes related to parallel scene conversion, @lordloki, @youle31 : Could you test again please ?

**Comment by lordloki** [comment]
Now all test blends under libload directory work except the componentlibload one. Same error relate to GIL when <mod = PyImport_ImportModule(pc->module);>

**Comment by youle31** [comment]
@panzergame : hello, your lasts commits seems to have fix the bug I was mentionning in my previous post. I tested only with Cotaks file named: libload_crashes_2.zip .

Else I can't reproduce the crash in master or elsewhere.

So everything works fine for me in the new ge_bug_fix_751 with this test file.

(offtopic: armatures ~work in eeveeInBge/upbge if you are interested)

**Comment by panzergame** [comment]
bea452bd7a45e9850b9f3e0ac3a64d050dfc9897 Is fixing a bug related to material merging, @lordloki, @youle31 : Is the status the same ?

**Comment by youle31** [comment]
About libload bug, with libload_crashes_2 test files I still have the issue in master. Everything works fine for me in ge_bug_fix_751

**Comment by lordloki** [comment]
I have rebase branch ge_bug_fix_751 with current master:
From Libload files from our test files:
- load.blend --> working
- mainUvTest.blend -> working
- MirrorLoad.blend -> crash
image
- AnimBugLoad.blend --> working
- componentLibLoad.blend --> crash
Same GIL problem as before
But if I change:
´´´c
Py_ALLOW_THREADS
Py_BLOCK_THREADS
blah bla bla
Py_UNBLOCK_THREADS;
Py_END_ALLOW_THREADS;
´´´
by 
´´´c
PyGILState_STATE gstate;
gstate = PyGILState_Ensure();

bla bla bla

PyGILState_Release(gstate);
´´´
Then blender doesn't crash but it hangs waiting finalize threads from FinalizeAsyncLoads functions
image

**Comment by panzergame** [comment]
MirrorLoad should be fixed now.

**Comment by lordloki** [comment]
MirrorLoad is fixed.

**Comment by lordloki** [comment]
@panzergame ComponentLibload Fixed!!! +10000 :-)

But now AniBugLoad.blend crash:

- Only crash when you spawn animated model.
- Only crash in release mode, not in debug
- Only crash if you "playAction". If only spawn the model didn't crash
- I moved the "playAction" code inside main blend (not requiring libload the sphere first) and also crash

**Comment by panzergame** [comment]
From last commit:

- AnimBugLoad : working in embedded and standalone (release build).

**Comment by lordloki** [comment]
@panzergame still crashing for me under win10 64bits (AnimBugLoad) after last commit.
I'm trying to generate a dump from reléase crash to can inspect it. I'm searching in the NET and it seems when this case occurs (release crash but debug not) can be related to (mainly):
- uninitialize variables
- writing past the end of a function local array

**Comment by lordloki** [comment]
Ok, using printf brute force method (as my first programming days...) I get that the crash is when I try to clear m_messages

image

**Comment by lordloki** [comment]
with 
```c
	if (m_messages[1 - m_currentList].empty()) {
		m_messages[1 - m_currentList].clear();
	}
```
Fix the crash but i think the fix is incorrect (as only clear when map is empty...)

**Comment by lordloki** [comment]
With Debugger/breakpoint all works as expected. No message is shown
image

Trying other things: I have introduced a real message with logic bricks and I commented message clean code, and this is the content of m_message. It seems that an external message is create always in `m_currentList=1`. This message can not be readed.

image

with this code

```c
void KX_NetworkMessageManager::ClearMessages()
{
	// Clear previous list.

	if (m_messages[1 - m_currentList].size() != 0) {
		CM_Debug("m_currentList = " << m_currentList);
		CM_Debug("m_messages = " << m_messages);
		CM_Debug("Size = " << m_messages[1 - m_currentList].size());
		
			for(auto const &ent1 : m_messages[1-m_currentList]) {
				// ent1.first is the first key
				CM_Debug("First key: " << ent1.first);
					for(auto const &ent2 : ent1.second) {
						CM_Debug("Second key: " << ent2.first);
						CM_Debug("Message: ");
						for (auto i = ent2.second.begin(); i != ent2.second.end(); ++i) {
							std::cout << "To:" << i->to << ' ' << "From:" << i->from << ' ' << "Subject:" << i->subject << ' ' << "Body:" << i->body << std::endl;
						}
					}
			}
	}
/*
	if (m_messages[1 - m_currentList].empty()) {
		CM_Debug("Limpiamos");
		m_messages[1 - m_currentList].clear();
	}
*/

	m_currentList = 1 - m_currentList;
	CM_Debug("");
}
```

**Comment by panzergame** [comment]
@lordloki : I compiled on windows and failed to reproduce the crash both in release and debug mode. Could you provide your file please ?

**Comment by lordloki** [comment]
[LibLoad.zip](https://github.com/UPBGE/blender/files/2298224/LibLoad.zip)
They are from UPBGE-Test files repository

I'm doing a totally clean and rebuild to see if it is a fault of my compilation

**Comment by panzergame** [comment]
If for you this PR is not introducing more issues, could we merge it has the related bug seems blocking ?

**Comment by youle31** [comment]
congrats!

**Pull request merged**
