### PR TITLE
UPBGE: Add unlimited Planar Reflections/Refractions Old branch

### PR DESCRIPTION
**Pull request by youle31**
I make another pull request with this branch to have better visibility of the code

### CODE REVIEW

**Comment by youle31** [comment]
@martinsh : I think it's ok now for clip planes for reflections. I didn't checked for refraction yet. Now you can have several planes with reflections.

**Comment by youle31** [comment]
test file for last commit about backface culling issues: http://pasteall.org/blend/index.php?id=43939

parenthesis: I remarked a slight performance decrease (860 fps against 880 before) with the test file above

**Comment by youle31** [comment]
test file: http://pasteall.org/blend/index.php?id=43945 (to test avoid reflections of other mirrors on a mirror)

For me it's stable enough (I fixed many crashes and free errors. I didn't really tested python API) to begin review, clean up and refactor eventually to have a commn base with cubemaps.

Some changes be done about names and tooltips.

**Comment by panzergame** [comment]
I'm thinking about changing the python API to receive the planar.

1) The object rendering to the texture will be accessed at:
```BL_Texture.render
or
BL_Texture.probe```
I don't know which is the best name, probe is fine for what we are doing: only rendering the scene from a position, but later maybe it will not be the main case, then `render`will be a better name…

2) The cube map and planar are using the same base python class:
```KX_TextureRenderer
or
KX_TextureProbe```

```KX_CubeMap(KX_Texture…)
KX_PlanarMap(KX_Texture…)
```

Not that the class rendering the planar reflection is named `KX_PanarMap` and not only `KX_Planar` to avoid confusions. It could be renamed differently like `KX_PlanarRenderer` but this will assume to also rename `KX_CubeMap`.

**Comment by youle31** [comment]
Hey, manu thanks for review.

My point is That sharing code to avoid repetitions could make the things harder to read for developers, debug for developers, and this lead to this kind of situation where it can also make things less readable and understandable for the user. For me, neither probe, neither render are explicit enough. For me the more intuitive for the user is: Texture.cubeMap.attr/method and texture.planarMap.attr/method. Else if your design choice is already made, I'd say: Texture.imageRendered.attr/method. Because the final goal would be to have all features of imageRender in UI. In UI, I put imageRender/mirror because I thought later we could have normal/mirror/viewports/video... If all this things have enough things in common, we could keep texture.imageRendered.attr/method. Else I'd add another sublevel and in this case we can be more explicit. Texture.imagerendered.mirror.attr/mthod. Texture.imagerendered.cubemap.attr/method, Texture.imagerendered.video.attr/method,
Texture.imagerendered.planarmap.attr/method... I think this is an important choice and that the API should more or less follow the design of the Ui (even if it is not totally possible because cubemap is in environment map tab and the others in image/imagerender (according to the UI I did). This needs to be thought with imagerender integration in the UI imho

**Comment by panzergame** [comment]
Moved to #390.

**Comment by youle31** [comment]
I reopen just to do the code comparison easier.

**Pull request closed without merging**
