### PR TITLE
Replacing Moto by Mathfu.

### PR DESCRIPTION
**Pull request by panzergame**

### CODE REVIEW

**Comment by Akira1San** [comment]
I dont know, if its for testing, but i did test the branch and the camera of my char goes to the bottom.
img; http://pasteall.org/pic/show.php?id=118375

**Comment by panzergame** [comment]
@Akira1San : Do you have a file which reproduce this issue ?

**Comment by Akira1San** [comment]
blend; https://drive.google.com/open?id=0B6yNvVGWiWysZW8wUXBNM3FqN2M

**Comment by youle31** [comment]
crash report in release mode with default cube pressing P:
- A first crash has been solved with this patch: http://pasteall.org/583034/diff
- For a second crash, debug picture: http://pasteall.org/pic/show.php?id=119051
- locals variables in visual studio: http://pasteall.org/583036/c when the crash happens
- Compilation warnings: http://pasteall.org/583047
- Compilation log: http://pasteall.org/583045
- blender.exe -d: http://pasteall.org/583050

Notes: 
- There are many warnings related to alignement when we compile with win 32 libs
- I noticed this message in compil log: set NOMINMAX as preprocessor macro, undefining min/max but I'm not sure it's relevant
- PyObjectPlus intellisense errors are not specific to ge_mathfu

exact steps to reproduce the crash:
- Build with Visual Studio 2013 update 5 in release with debug infos with windows 32 bits libs
- open a blender.exe, Blender Game, and press P

**Comment by panzergame** [comment]
Done.

**Pull request closed without merging**
