### PR TITLE
UPBGE: Add an option to enable/disable casting shadow per object

### PR DESCRIPTION
**Pull request by youle31**
This could be used to perform kind of LOD system for shadows casting.
Performance tests could be done to see if this method saves performances
or not.

test file: http://pasteall.org/blend/index.php?id=43407
video: https://youtu.be/gGaER6iELQM

### CODE REVIEW

**Comment by panzergame** [comment]
youle: Do you think a per object layer system `KX_GameObject.layer` will be simpler ?

**Comment by panzergame** [comment]
For example use the `KX_GameObject::[Get/Set]Layer`, normally it should work as it.

**Comment by youle31** [comment]
Kxgameobject::layer? I don't understand... I Just imitated the cast shadow option as it Is in the viewport - i mean don't rendre object when we are in shadow rendering pass. Except That i simplifier it because i don't know why in viewport the option is a material option instead of an object option... I Just answered very simply to akira-san request. M'y code is very simple and i guess efficient because the geometry mightt not been rendered because the object is culled.

**Comment by youle31** [comment]
About layers system, do you mean that the object would cast shadows from lights in a layer and don't cast shadows from lights in other layers?

If it's that, this is not the same as my option and could be another option eventually.

The patch I implemented disables shadows casted by this object for all lights in all layers... I think it can be merged as it is.

**Comment by youle31** [comment]
I think this simple commit doesn't prevent to make another API with layers if you want (I didn't understood exactly how you wanted to design that) so I think it's ready to land.

**Comment by youle31** [comment]
And this?

**Comment by panzergame** [comment]
I prefered a system with object render layer:

object.layer & light.layer ---> shadow

This is planned for 0.1.3 currently but if you have time you can start working on.

**Comment by youle31** [comment]
This is not the same option. Your option with layers doesn't exclude the possibility to have another option to castShadows as in the viewport. And castShadows is easy to use even if it is not per light. The system with layers would be more for advanced users

**Comment by panzergame** [comment]
Imagine you have two shadows buffer, one low resolution and the other high resolution, you will want to select which buffer will be used. With a layer it's possible as the it is not global to all the shadows buffer.

**Comment by youle31** [comment]
Yes it's fine... But what i say is That both options can ne added

**Comment by panzergame** [comment]
What about move the castShadow in KX_BlenderMaterial as for the UI and the layer only in object ?

**Comment by youle31** [comment]
There is no ui in m'y patch. I don't understand why cast shadows option was in material tab . It seems a bit weird to me to Say material.castshadow... This Is not the material That cast shadows... Object.castshadows seems to me much intuitive and avoid a for each material loop

**Comment by youle31** [comment]
As it is not an important feature and as it is difficult to find overall agreement on the subject, I close this pull request.

**Pull request closed without merging**
