### PR TITLE
UPBGE: Makes distance and angle python attributes for Radar Sensor

### PR DESCRIPTION
**Pull request by lordloki**
writables

This patch adds the posibility to modify the radar cone's distance and
angle attributes during the runtime through BGE python.

Credits for this patch goes to @Kseniya Halezova (blenderprowlee) too.

An example to can check the feature http://pasteall.org/blend/index.php?
id=44156

### CODE REVIEW

**Comment by ondredeniso** [comment]
Thanks you. Looks like useful feature.

**Comment by youle31** [comment]
Hi, for me this is good.

Just 2 comments/questions:
1) For the bullet patch, I think the patch won't apply on my PC for example because there is no new line at end of file.
2) I still use PyErr_SetString in my own patches but I was wondering if this had changed. We have to use something else now? CM_Error or something like that? CM means colored message? I'll check.

**Comment by lordloki** [comment]
@youle, I will take a look. thanks :-)

**Comment by youle31** [comment]
Sorry I finally tested and the bullet patch applies correctly.

**Pull request closed without merging**
