### PR TITLE
In ge_filter, replace setTexture(m_textures index, bindcode) with setTexture(name, bindcode)

### PR DESCRIPTION
**Pull request by youle31**
test file: http://www.pasteall.org/blend/41793

### CODE REVIEW

**Comment by youle31** [comment]
@DCubix : Hey! Could I ask what do you think of the last commit? I leaved explainations... Panzergame would like to have your opinion too. He was not convinced that we should setTexture for 2D filter in a single step instead of two. Thanks!

**Comment by panzergame** [comment]
The issue with setTexture is that is it based on previous non-existing bindcode (=0), but if the texture bindcode changed e.g VideoTexture, how the user will be able to overwrite the previous invalid bindcode ?

It's why i prefer the setTexture(index, bindcode) because it explicitly overwrite the emplacement "index" with "bindcode".

**Comment by youle31** [comment]
Yes. This Is why i propose to add a third optionnal arg to choose to force m-texture index

**Comment by youle31** [comment]
will replace with another method

**Pull request closed without merging**
