### PR TITLE
UPBGE: replace setIdentity each frame with const matrix

### PR DESCRIPTION
**Pull request by youle31**
In RAS_2DFilter::Start, each frame a MT_Matrix4x4 was created and set to
identity. I replaced it with static const mat already set to identity.

### CODE REVIEW

**Comment by panzergame** [comment]
An equivalent is `MT_Matrix4x4 mat = MT_Matrix4x4::Identity();`, else can you find similar case in the code ?

**Comment by panzergame** [comment]
I'm wrong sorry

**Comment by youle31** [comment]
No, I didn't searched similar case in the code. I just did the modif as I thought that setting matrix each frame was not needed

**Comment by youle31** [comment]
I'll maybe do another patch to replace static matrix with a member matrix

**Pull request closed without merging**
