### PR TITLE
Material switching.

### PR DESCRIPTION
**Pull request by panzergame**
This branch allow the user to replace a material by calling in python:
```
mesh.replaceMaterial(index, material)
```

Then the material in the slot `index`will be replaced by the material `material`.

When the material is replaced the RAS_DisplayArrayBucket are moved to the RAS_BucketMaterial of the new material, all the mesh slot in this DAB reset their pointer to the material bucket and the attribute's layers are recomputed to follow the new material.

@lordloki, @DCubix, @sdfgeoff: Do you agree with the API and the patch ? Could you make some test to find any possible bugs ? Thanks in advance.

### CODE REVIEW

**Comment by youle31** [comment]
Congrats panzergame! I just tested with this file: http://pasteall.org/blend/index.php?id=43839 and it looks to work fine :) Would it be easy to add an optional argument to replace texture at the same time than material?

**Comment by youle31** [comment]
A weird effect with this file: http://pasteall.org/blend/index.php?id=43861 (the texture can change if the material we change had a texture)

**Comment by panzergame** [comment]
@youle31 : The texture is containing the textures, if you change it you change the texture. Did i answered correctly and understand the question ?

**Comment by youle31** [comment]
I meant:
- When you change a material that has no texture with a material that has texture, the new material has no texture.
- When you change a material that has a texture with a material that has texture, the new material has the new texture.

**Comment by youle31** [comment]
For me it's good.

**Pull request closed without merging**
