### PR TITLE
UPBGE: Vibration Actuator improvement

### PR DESCRIPTION
**Pull request by lordloki**
Now the vibration actuator has 2 methods (start and stop). Start method
starts the vibration and also it can update the parameters of the
vibration on fly. Stop method stops the vibration.

Now there is 2 strenght parameters the "left" one sets the strenght of
the Low frequency joystick's motor and the "right" one sets the strenght
of the High frequency joystick's motor.

Additionaly, 2 new bool attributes have been included (isVibrating and
hasVibration) along the new python methods.

### CODE REVIEW

**Comment by panzergame** [comment]
@lordloki : pushed some review changes in ge_vibration_leftright. I also noticed an issue:
It appears sometimes that the controller failed run any rumble at game start, when i debug effect creation i see that it is always creating an new effect even i the duration is not over. `(m_private->m_hapticEffectStatus == JOYHAPTIC_UPDATING_EFFECT)` seems to be false even at game start.

**Comment by lordloki** [comment]
@panzergame: I will debug it to see where is the issue.

**Comment by lordloki** [comment]
@panzergame: A fix was pushed. Could you check it again?

**Comment by panzergame** [comment]
@lordloki : Thanks, the bug seems fixed now.

**Comment by lordloki** [comment]
OK, then I close this pull request and open the pull request from ge_vibration_leftright branch

**Pull request closed without merging**
