### PR TITLE
UPBGE: Cleanup UI.

### PR DESCRIPTION
**Pull request by panzergame**
Some unused options/entities are removed from the UI in game engine mode:
- scene keying set
- scene audio
- speaker and forec filed in add menu

Also the game engine is renamed UPBGE.

Fix issue #756.

### CODE REVIEW

**Comment by marechal-p** [comment]
> I'd like to point that a speaker is much more intuitive to the new user to be a "sound reproducer".It will increase the discoverabilty of these feature (sound) in the engine. And, of couse, even for the experienced user, having a GameObject that is alrady prepared to reproduce sounds, without any other configuration, will increase the development speed.

That's an issue on its own that deserves its own PR. Better remove the item from the UI until it has an actual purpose.

**Comment by youle31** [comment]
I agree with this patch and I agree both with @UnidayStudio  and @marechal-p remarks

**Comment by UnidayStudio** [comment]
We can remove Area lights as well

**Comment by panzergame** [comment]
I can't remove AREA in the lamp type enum because the front end UI doesn't provide a way to filter enum properties.
Otherwise it possible to replace the UI of area lamp by a message like 'not supported in game engine'.

**Comment by panzergame** [comment]
@lordloki : The function using these variables is:
```c
void BKE_sound_update_scene_listener(struct Scene *scene)
{
	AUD_Sequence_setSpeedOfSound(scene->sound_scene, scene->audio.speed_of_sound);
	AUD_Sequence_setDopplerFactor(scene->sound_scene, scene->audio.doppler_factor);
	AUD_Sequence_setDistanceModel(scene->sound_scene, scene->audio.distance_model);
}

```

Though it is using `scene->sound_scene` which doesn't seems global or registered to a global variable and also not used by the game engine. The type of AUD_Sound is also strange.

I didn't do a deep research, @lordloki : Do you have a example of these values used in game ?

**Comment by panzergame** [comment]
@lordloki : These attributes are now exposed.

**Comment by lordloki** [comment]
@panzergame I have a issue with audio panel when revert to other render from UPBGE.

Fix plus cosmetic refactor: https://gist.github.com/lordloki/a34ef600e1255f4b93d087eaaf7505e9

**Pull request merged**
