### PR TITLE
Physically-Based Shader and World Ambient Fix

### PR DESCRIPTION
**Pull request by DCubix**
In this branch, I implemented a basic PBS by modifying the original Cook-Torrance specular model. Now it has 2 parameters: Roughness and Metallic.
Roughness: How hard the surface is. (0 = smooth, 1 = hard)
Metallic: Glossiness amount. (0 = no glossiness, 4 = full gloss)

Screenshot:
selection_061

I also fixed how the World ambient color was applied to the scene. Here's a comparison:
Old:
selection_062

New:
selection_063

That's it for now :+1:

### CODE REVIEW

**Comment by adriansnetlis** [comment]
It seams to be good thing. Question - are you using inverted hardness value in texture tab for roughness?

**Comment by youle31** [comment]
This is great! Thanks TwisterGE

**Comment by BluePrintRandom** [comment]
Nice work gentlemen!

Environment maps soon in that?

is it a second material set, or it overrides the old phong shader?

**Comment by panzergame** [comment]
@DCubix: For the moment what can i use ? you said me sometimes ago that ambient color was not working.

**Pull request closed without merging**
