### PR TITLE
UPBGE: Display "Invalid Uniform Value" error message only at the firs…

### PR DESCRIPTION
**Pull request by youle31**
…t run

This is to avoid to fill the console with repeated error messages each
frame. This is related to https://github.com/UPBGE/blender/issues/319

test file: http://pasteall.org/blend/index.php?id=44739
better test file: http://pasteall.org/blend/index.php?id=44742

### CODE REVIEW

**Comment by panzergame** [comment]
@youle31 : i don't really see what we need to avoid error message repeat, if there's an error print it, don't try to make it more quiet. Also for 2d filter: it will not print an error for each unused object properties now ?

**Comment by youle31** [comment]
@panzergame: the reason is explained here: #319

Else you're right, I restore debug

**Comment by youle31** [comment]
For this I don't know, I feel not really concerned but it was just to answer a feature request. If a better alternative is found, I can close this request.

**Comment by youle31** [comment]
Not important enough. I close

**Pull request closed without merging**
